import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import './globals.scss';

const font = Poppins({ style: 'normal', weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={font.className}>{children}</body>
        </html>
    );
}
