import type { Metadata } from 'next';
import { Atkinson_Hyperlegible } from 'next/font/google';

import Sidebar from './_components/Sidebar';
import './globals.scss';
import { Providers } from './providers';

const font = Atkinson_Hyperlegible({
    style: 'normal',
    weight: ['400', '700'],
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={font.className}>
                <Providers>
                    <Sidebar />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
