name: Run migrations

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-migrations:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Run migrations
        run: supabase migrate up --project $PROJECT_ID --key $SUPABASE_ACCESS_TOKEN
