name: Run Supabase tests

on:
  push:
  workflow_dispatch:

jobs:
  run-supabase-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - uses: actions/setup-node@latest
        with:
          node-version: "20"
      - run: supabase start
      - run: npm run test:supabase
